"""Initial migration.

Revision ID: 10c754cbf1b3
Revises: 
Create Date: 2020-03-07 00:34:42.400759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10c754cbf1b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flask_content_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_label', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('flask_content_type_app_label_model_76bd3d3b_uniq', 'flask_content_type', ['app_label', 'model'], unique=True)
    op.create_table('accounts_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('phone_number', sa.String(length=17), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=17), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('accounts_user_groups_user_id_group_id_59c0b32f_uniq', 'accounts_user_groups', ['user_id', 'group_id'], unique=True)
    op.create_index(op.f('ix_accounts_user_groups_group_id'), 'accounts_user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_groups_user_id'), 'accounts_user_groups', ['user_id'], unique=False)
    op.create_table('auth_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_type_id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['flask_content_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', 'auth_permission', ['content_type_id', 'codename'], unique=True)
    op.create_index(op.f('ix_auth_permission_content_type_id'), 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('accounts_user_user_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['accounts_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_user_permissions_permission_id'), 'accounts_user_user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_accounts_user_user_permissions_user_id'), 'accounts_user_user_permissions', ['user_id'], unique=False)
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_group_permissions_group_id'), 'auth_group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_auth_group_permissions_permission_id'), 'auth_group_permissions', ['permission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_group_permissions_permission_id'), table_name='auth_group_permissions')
    op.drop_index(op.f('ix_auth_group_permissions_group_id'), table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_index(op.f('ix_accounts_user_user_permissions_user_id'), table_name='accounts_user_user_permissions')
    op.drop_index(op.f('ix_accounts_user_user_permissions_permission_id'), table_name='accounts_user_user_permissions')
    op.drop_table('accounts_user_user_permissions')
    op.drop_index(op.f('ix_auth_permission_content_type_id'), table_name='auth_permission')
    op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_index(op.f('ix_accounts_user_groups_user_id'), table_name='accounts_user_groups')
    op.drop_index(op.f('ix_accounts_user_groups_group_id'), table_name='accounts_user_groups')
    op.drop_index('accounts_user_groups_user_id_group_id_59c0b32f_uniq', table_name='accounts_user_groups')
    op.drop_table('accounts_user_groups')
    op.drop_table('accounts_profile')
    op.drop_index('flask_content_type_app_label_model_76bd3d3b_uniq', table_name='flask_content_type')
    op.drop_table('flask_content_type')
    op.drop_table('auth_group')
    op.drop_table('accounts_user')
    # ### end Alembic commands ###
